#!/bin/bash

set -e

NAZS_USER='nazs'
NAZS_HOME='/var/lib/nazs/'

case "$1" in
    configure)
        # Create NAZS user
        if ! getent passwd $NAZS_USER 2>&1 > /dev/null
        then
            adduser --system --home "$NAZS_HOME" $NAZS_USER
        fi

        dpkg-trigger --no-await nazs
    ;;

    triggered)
        # Setup/migrate conf database
        if [ -f $NAZS_DB ]; then
            echo Upgrading NAZS database...
        else
            echo Creating NAZS database...
        fi
        /usr/bin/nazs migrate --noinput
    ;;
esac

exit 0
